Vagrant.configure(2) do |config|
  config.vm.define "web" do |web|
    web.vm.network :forwarded_port, guest: 80, host: 80
    web.vm.hostname = "web"
    web.vm.provider "docker" do |docker|
      docker.vagrant_vagrantfile = __FILE__
      docker.vagrant_machine = "docker-host"
      docker.image = "nginx"
    end
  end
  config.vm.define "docker-host", auto_start: false do |dockerHost|
    dockerHost.vm.hostname = "docker-host"
    dockerHost.vm.box = "yogendra/docker-vmware"
  end
end